// Curated database of top Indian and international cities for instant 0ms autocomplete
export const POPULAR_CITIES = [
  // Karnataka & South India
  { name: 'Mysore', region: 'Karnataka', country: 'India' },
  { name: 'Bengaluru', region: 'Karnataka', country: 'India' },
  { name: 'Mangalore', region: 'Karnataka', country: 'India' },
  { name: 'Hubli', region: 'Karnataka', country: 'India' },
  { name: 'Belgaum', region: 'Karnataka', country: 'India' },
  { name: 'Davanagere', region: 'Karnataka', country: 'India' },
  { name: 'Bellary', region: 'Karnataka', country: 'India' },
  { name: 'Bijapur', region: 'Karnataka', country: 'India' },
  { name: 'Shimoga', region: 'Karnataka', country: 'India' },
  { name: 'Tumakuru', region: 'Karnataka', country: 'India' },
  { name: 'Gulbarga', region: 'Karnataka', country: 'India' },
  { name: 'Raichur', region: 'Karnataka', country: 'India' },
  { name: 'Bidar', region: 'Karnataka', country: 'India' },
  { name: 'Hospet', region: 'Karnataka', country: 'India' },
  { name: 'Gadag', region: 'Karnataka', country: 'India' },
  { name: 'Hassan', region: 'Karnataka', country: 'India' },
  { name: 'Udupi', region: 'Karnataka', country: 'India' },
  { name: 'Chitradurga', region: 'Karnataka', country: 'India' },
  { name: 'Kolar', region: 'Karnataka', country: 'India' },
  { name: 'Mandya', region: 'Karnataka', country: 'India' },
  { name: 'Chikmagalur', region: 'Karnataka', country: 'India' },
  { name: 'Bagalkot', region: 'Karnataka', country: 'India' },
  { name: 'Karwar', region: 'Karnataka', country: 'India' },
  { name: 'Ramanagara', region: 'Karnataka', country: 'India' },
  { name: 'Chamarajanagar', region: 'Karnataka', country: 'India' },
  { name: 'Yadgir', region: 'Karnataka', country: 'India' },
  { name: 'Koppal', region: 'Karnataka', country: 'India' },
  { name: 'Haveri', region: 'Karnataka', country: 'India' },
  { name: 'Madikeri', region: 'Karnataka', country: 'India' },
  { name: 'Chennai', region: 'Tamil Nadu', country: 'India' },
  { name: 'Coimbatore', region: 'Tamil Nadu', country: 'India' },
  { name: 'Madurai', region: 'Tamil Nadu', country: 'India' },
  { name: 'Tiruchirappalli', region: 'Tamil Nadu', country: 'India' },
  { name: 'Salem', region: 'Tamil Nadu', country: 'India' },
  { name: 'Tirunelveli', region: 'Tamil Nadu', country: 'India' },
  { name: 'Erode', region: 'Tamil Nadu', country: 'India' },
  { name: 'Vellore', region: 'Tamil Nadu', country: 'India' },
  { name: 'Hyderabad', region: 'Telangana', country: 'India' },
  { name: 'Warangal', region: 'Telangana', country: 'India' },
  { name: 'Nizamabad', region: 'Telangana', country: 'India' },
  { name: 'Karimnagar', region: 'Telangana', country: 'India' },
  { name: 'Visakhapatnam', region: 'Andhra Pradesh', country: 'India' },
  { name: 'Vijayawada', region: 'Andhra Pradesh', country: 'India' },
  { name: 'Guntur', region: 'Andhra Pradesh', country: 'India' },
  { name: 'Nellore', region: 'Andhra Pradesh', country: 'India' },
  { name: 'Kurnool', region: 'Andhra Pradesh', country: 'India' },
  { name: 'Rajahmundry', region: 'Andhra Pradesh', country: 'India' },
  { name: 'Tirupati', region: 'Andhra Pradesh', country: 'India' },
  { name: 'Kochi', region: 'Kerala', country: 'India' },
  { name: 'Thiruvananthapuram', region: 'Kerala', country: 'India' },
  { name: 'Kozhikode', region: 'Kerala', country: 'India' },
  { name: 'Thrissur', region: 'Kerala', country: 'India' },
  { name: 'Kollam', region: 'Kerala', country: 'India' },

  // Major Indian Metros & Capitals
  { name: 'Mumbai', region: 'Maharashtra', country: 'India' },
  { name: 'Pune', region: 'Maharashtra', country: 'India' },
  { name: 'Nagpur', region: 'Maharashtra', country: 'India' },
  { name: 'Thane', region: 'Maharashtra', country: 'India' },
  { name: 'Nashik', region: 'Maharashtra', country: 'India' },
  { name: 'Aurangabad', region: 'Maharashtra', country: 'India' },
  { name: 'Solapur', region: 'Maharashtra', country: 'India' },
  { name: 'Amravati', region: 'Maharashtra', country: 'India' },
  { name: 'Kolhapur', region: 'Maharashtra', country: 'India' },
  { name: 'Delhi', region: 'Delhi', country: 'India' },
  { name: 'New Delhi', region: 'Delhi', country: 'India' },
  { name: 'Noida', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Greater Noida', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Ghaziabad', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Gurgaon', region: 'Haryana', country: 'India' },
  { name: 'Faridabad', region: 'Haryana', country: 'India' },
  { name: 'Kolkata', region: 'West Bengal', country: 'India' },
  { name: 'Howrah', region: 'West Bengal', country: 'India' },
  { name: 'Durgapur', region: 'West Bengal', country: 'India' },
  { name: 'Asansol', region: 'West Bengal', country: 'India' },
  { name: 'Siliguri', region: 'West Bengal', country: 'India' },
  { name: 'Ahmedabad', region: 'Gujarat', country: 'India' },
  { name: 'Surat', region: 'Gujarat', country: 'India' },
  { name: 'Vadodara', region: 'Gujarat', country: 'India' },
  { name: 'Rajkot', region: 'Gujarat', country: 'India' },
  { name: 'Bhavnagar', region: 'Gujarat', country: 'India' },
  { name: 'Jamnagar', region: 'Gujarat', country: 'India' },
  { name: 'Gandhinagar', region: 'Gujarat', country: 'India' },
  { name: 'Jaipur', region: 'Rajasthan', country: 'India' },
  { name: 'Jodhpur', region: 'Rajasthan', country: 'India' },
  { name: 'Kota', region: 'Rajasthan', country: 'India' },
  { name: 'Bikaner', region: 'Rajasthan', country: 'India' },
  { name: 'Ajmer', region: 'Rajasthan', country: 'India' },
  { name: 'Udaipur', region: 'Rajasthan', country: 'India' },
  { name: 'Lucknow', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Kanpur', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Varanasi', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Agra', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Prayagraj', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Meerut', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Bareilly', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Aligarh', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Moradabad', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Saharanpur', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Gorakhpur', region: 'Uttar Pradesh', country: 'India' },
  { name: 'Bhopal', region: 'Madhya Pradesh', country: 'India' },
  { name: 'Indore', region: 'Madhya Pradesh', country: 'India' },
  { name: 'Jabalpur', region: 'Madhya Pradesh', country: 'India' },
  { name: 'Gwalior', region: 'Madhya Pradesh', country: 'India' },
  { name: 'Ujjain', region: 'Madhya Pradesh', country: 'India' },
  { name: 'Patna', region: 'Bihar', country: 'India' },
  { name: 'Gaya', region: 'Bihar', country: 'India' },
  { name: 'Bhagalpur', region: 'Bihar', country: 'India' },
  { name: 'Muzaffarpur', region: 'Bihar', country: 'India' },
  { name: 'Bhubaneswar', region: 'Odisha', country: 'India' },
  { name: 'Cuttack', region: 'Odisha', country: 'India' },
  { name: 'Rourkela', region: 'Odisha', country: 'India' },
  { name: 'Puri', region: 'Odisha', country: 'India' },
  { name: 'Chandigarh', region: 'Chandigarh', country: 'India' },
  { name: 'Ludhiana', region: 'Punjab', country: 'India' },
  { name: 'Amritsar', region: 'Punjab', country: 'India' },
  { name: 'Jalandhar', region: 'Punjab', country: 'India' },
  { name: 'Patiala', region: 'Punjab', country: 'India' },
  { name: 'Ranchi', region: 'Jharkhand', country: 'India' },
  { name: 'Jamshedpur', region: 'Jharkhand', country: 'India' },
  { name: 'Dhanbad', region: 'Jharkhand', country: 'India' },
  { name: 'Bokaro', region: 'Jharkhand', country: 'India' },
  { name: 'Raipur', region: 'Chhattisgarh', country: 'India' },
  { name: 'Bhilai', region: 'Chhattisgarh', country: 'India' },
  { name: 'Bilaspur', region: 'Chhattisgarh', country: 'India' },
  { name: 'Guwahati', region: 'Assam', country: 'India' },
  { name: 'Silchar', region: 'Assam', country: 'India' },
  { name: 'Dehradun', region: 'Uttarakhand', country: 'India' },
  { name: 'Haridwar', region: 'Uttarakhand', country: 'India' },
  { name: 'Nainital', region: 'Uttarakhand', country: 'India' },
  { name: 'Shimla', region: 'Himachal Pradesh', country: 'India' },
  { name: 'Manali', region: 'Himachal Pradesh', country: 'India' },
  { name: 'Dharamshala', region: 'Himachal Pradesh', country: 'India' },
  { name: 'Srinagar', region: 'Jammu and Kashmir', country: 'India' },
  { name: 'Jammu', region: 'Jammu and Kashmir', country: 'India' },
  { name: 'Panaji', region: 'Goa', country: 'India' },
  { name: 'Vasco da Gama', region: 'Goa', country: 'India' },
  { name: 'Puducherry', region: 'Puducherry', country: 'India' },
  { name: 'Port Blair', region: 'Andaman and Nicobar Islands', country: 'India' },
  { name: 'Gangtok', region: 'Sikkim', country: 'India' },
  { name: 'Shillong', region: 'Meghalaya', country: 'India' },
  { name: 'Imphal', region: 'Manipur', country: 'India' },
  { name: 'Aizawl', region: 'Mizoram', country: 'India' },
  { name: 'Kohima', region: 'Nagaland', country: 'India' },
  { name: 'Agartala', region: 'Tripura', country: 'India' },
  { name: 'Itanagar', region: 'Arunachal Pradesh', country: 'India' },

  // Major International Cities
  { name: 'London', region: 'England', country: 'United Kingdom' },
  { name: 'Manchester', region: 'England', country: 'United Kingdom' },
  { name: 'Birmingham', region: 'England', country: 'United Kingdom' },
  { name: 'Edinburgh', region: 'Scotland', country: 'United Kingdom' },
  { name: 'Glasgow', region: 'Scotland', country: 'United Kingdom' },
  { name: 'Paris', region: 'Ile-de-France', country: 'France' },
  { name: 'Marseille', region: 'Provence-Alpes-Cote d\'Azur', country: 'France' },
  { name: 'Lyon', region: 'Auvergne-Rhone-Alpes', country: 'France' },
  { name: 'New York', region: 'New York', country: 'United States' },
  { name: 'Los Angeles', region: 'California', country: 'United States' },
  { name: 'Chicago', region: 'Illinois', country: 'United States' },
  { name: 'Houston', region: 'Texas', country: 'United States' },
  { name: 'Phoenix', region: 'Arizona', country: 'United States' },
  { name: 'Philadelphia', region: 'Pennsylvania', country: 'United States' },
  { name: 'San Antonio', region: 'Texas', country: 'United States' },
  { name: 'San Diego', region: 'California', country: 'United States' },
  { name: 'Dallas', region: 'Texas', country: 'United States' },
  { name: 'San Jose', region: 'California', country: 'United States' },
  { name: 'Austin', region: 'Texas', country: 'United States' },
  { name: 'San Francisco', region: 'California', country: 'United States' },
  { name: 'Seattle', region: 'Washington', country: 'United States' },
  { name: 'Denver', region: 'Colorado', country: 'United States' },
  { name: 'Washington', region: 'District of Columbia', country: 'United States' },
  { name: 'Boston', region: 'Massachusetts', country: 'United States' },
  { name: 'Miami', region: 'Florida', country: 'United States' },
  { name: 'Las Vegas', region: 'Nevada', country: 'United States' },
  { name: 'Atlanta', region: 'Georgia', country: 'United States' },
  { name: 'Orlando', region: 'Florida', country: 'United States' },
  { name: 'Tokyo', region: 'Tokyo', country: 'Japan' },
  { name: 'Osaka', region: 'Osaka', country: 'Japan' },
  { name: 'Kyoto', region: 'Kyoto', country: 'Japan' },
  { name: 'Yokohama', region: 'Kanagawa', country: 'Japan' },
  { name: 'Dubai', region: 'Dubai', country: 'United Arab Emirates' },
  { name: 'Abu Dhabi', region: 'Abu Dhabi', country: 'United Arab Emirates' },
  { name: 'Sharjah', region: 'Sharjah', country: 'United Arab Emirates' },
  { name: 'Singapore', region: 'Singapore', country: 'Singapore' },
  { name: 'Sydney', region: 'New South Wales', country: 'Australia' },
  { name: 'Melbourne', region: 'Victoria', country: 'Australia' },
  { name: 'Brisbane', region: 'Queensland', country: 'Australia' },
  { name: 'Perth', region: 'Western Australia', country: 'Australia' },
  { name: 'Toronto', region: 'Ontario', country: 'Canada' },
  { name: 'Vancouver', region: 'British Columbia', country: 'Canada' },
  { name: 'Montreal', region: 'Quebec', country: 'Canada' },
  { name: 'Berlin', region: 'Berlin', country: 'Germany' },
  { name: 'Munich', region: 'Bavaria', country: 'Germany' },
  { name: 'Frankfurt', region: 'Hesse', country: 'Germany' },
  { name: 'Rome', region: 'Lazio', country: 'Italy' },
  { name: 'Milan', region: 'Lombardy', country: 'Italy' },
  { name: 'Madrid', region: 'Madrid', country: 'Spain' },
  { name: 'Barcelona', region: 'Catalonia', country: 'Spain' },
  { name: 'Amsterdam', region: 'North Holland', country: 'Netherlands' },
  { name: 'Brussels', region: 'Brussels-Capital', country: 'Belgium' },
  { name: 'Vienna', region: 'Vienna', country: 'Austria' },
  { name: 'Zurich', region: 'Zurich', country: 'Switzerland' },
  { name: 'Geneva', region: 'Geneva', country: 'Switzerland' },
  { name: 'Bangkok', region: 'Bangkok', country: 'Thailand' },
  { name: 'Kuala Lumpur', region: 'Federal Territory of Kuala Lumpur', country: 'Malaysia' },
  { name: 'Jakarta', region: 'Jakarta', country: 'Indonesia' },
  { name: 'Bali', region: 'Bali', country: 'Indonesia' },
  { name: 'Manila', region: 'National Capital Region', country: 'Philippines' },
  { name: 'Seoul', region: 'Seoul', country: 'South Korea' },
  { name: 'Beijing', region: 'Beijing', country: 'China' },
  { name: 'Shanghai', region: 'Shanghai', country: 'China' },
  { name: 'Hong Kong', region: 'Hong Kong', country: 'Hong Kong' },
  { name: 'Taipei', region: 'Taipei', country: 'Taiwan' },
  { name: 'Cairo', region: 'Cairo', country: 'Egypt' },
  { name: 'Johannesburg', region: 'Gauteng', country: 'South Africa' },
  { name: 'Cape Town', region: 'Western Cape', country: 'South Africa' },
  { name: 'Nairobi', region: 'Nairobi Area', country: 'Kenya' },
  { name: 'Istanbul', region: 'Istanbul', country: 'Turkey' },
  { name: 'Athens', region: 'Attica', country: 'Greece' },
  { name: 'Lisbon', region: 'Lisbon', country: 'Portugal' },
  { name: 'Dublin', region: 'Leinster', country: 'Ireland' },
  { name: 'Copenhagen', region: 'Capital Region', country: 'Denmark' },
  { name: 'Stockholm', region: 'Stockholm', country: 'Sweden' },
  { name: 'Oslo', region: 'Oslo', country: 'Norway' },
  { name: 'Helsinki', region: 'Uusimaa', country: 'Finland' },
  { name: 'Prague', region: 'Prague', country: 'Czech Republic' },
  { name: 'Budapest', region: 'Budapest', country: 'Hungary' },
  { name: 'Warsaw', region: 'Mazovia', country: 'Poland' },
  { name: 'Doha', region: 'Ad Dawhah', country: 'Qatar' },
  { name: 'Riyadh', region: 'Ar Riyad', country: 'Saudi Arabia' },
  { name: 'Kuwait City', region: 'Al Asimah', country: 'Kuwait' },
  { name: 'Muscat', region: 'Masqat', country: 'Oman' },
  { name: 'Colombo', region: 'Western', country: 'Sri Lanka' },
  { name: 'Kathmandu', region: 'Bagmati', country: 'Nepal' },
  { name: 'Dhaka', region: 'Dhaka', country: 'Bangladesh' },
  { name: 'Mexico City', region: 'Distrito Federal', country: 'Mexico' },
  { name: 'Sao Paulo', region: 'Sao Paulo', country: 'Brazil' },
  { name: 'Rio de Janeiro', region: 'Rio de Janeiro', country: 'Brazil' },
  { name: 'Buenos Aires', region: 'Distrito Federal', country: 'Argentina' },
  { name: 'Santiago', region: 'Region Metropolitana', country: 'Chile' },
  { name: 'Auckland', region: 'Auckland', country: 'New Zealand' }
];

export function findMatchingCities(query, limit = 8) {
  if (!query || typeof query !== 'string') return [];
  const q = query.trim().toLowerCase();
  if (q.length === 0) return [];

  const exactStarts = [];
  const wordStarts = [];
  const contains = [];

  for (const city of POPULAR_CITIES) {
    const nameLower = city.name.toLowerCase();
    const regionLower = (city.region || '').toLowerCase();
    const countryLower = (city.country || '').toLowerCase();

    if (nameLower.startsWith(q)) {
      exactStarts.push(city);
    } else if (nameLower.split(' ').some(w => w.startsWith(q))) {
      wordStarts.push(city);
    } else if (nameLower.includes(q) || regionLower.includes(q) || countryLower.includes(q)) {
      contains.push(city);
    }

    if (exactStarts.length + wordStarts.length >= limit * 2) {
      break;
    }
  }

  return [...exactStarts, ...wordStarts, ...contains].slice(0, limit);
}
